//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/parser/AttrI.java
//

#ifndef _AttrI_H_
#define _AttrI_H_

#include "J2ObjC_header.h"
#include "NodeI.h"
#include "Attr.h"

@protocol OrgW3cDomAttr;

@interface AttrI : NodeI < RXAttr > {
 @public
  id<OrgW3cDomAttr> impl_AttrI_;
}

#pragma mark Public

- (instancetype)initWithOrgW3cDomAttr:(id<OrgW3cDomAttr>)impl;

- (NSString *)getName;

- (NSString *)getValue;

- (jboolean)isSpecified;

@end

J2OBJC_EMPTY_STATIC_INIT(AttrI)

J2OBJC_FIELD_SETTER(AttrI, impl_AttrI_, id<OrgW3cDomAttr>)

FOUNDATION_EXPORT void AttrI_initWithOrgW3cDomAttr_(AttrI *self, id<OrgW3cDomAttr> impl);

FOUNDATION_EXPORT AttrI *new_AttrI_initWithOrgW3cDomAttr_(id<OrgW3cDomAttr> impl) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AttrI)

typedef AttrI RXAttrI;

#endif // _AttrI_H_
