//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/parser/DocumentI.java
//

#ifndef _DocumentI_H_
#define _DocumentI_H_

#include "J2ObjC_header.h"
#include "Document.h"

@protocol RXElement;
@protocol OrgW3cDomDocument;

@interface DocumentI : NSObject < RXDocument >

#pragma mark Public

- (instancetype)initWithOrgW3cDomDocument:(id<OrgW3cDomDocument>)impl;

- (id<RXElement>)getDocumentElement;

@end

J2OBJC_EMPTY_STATIC_INIT(DocumentI)

FOUNDATION_EXPORT void DocumentI_initWithOrgW3cDomDocument_(DocumentI *self, id<OrgW3cDomDocument> impl);

FOUNDATION_EXPORT DocumentI *new_DocumentI_initWithOrgW3cDomDocument_(id<OrgW3cDomDocument> impl) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(DocumentI)

typedef DocumentI RXDocumentI;

#endif // _DocumentI_H_
