//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/parser/ElementI.java
//

#ifndef _ElementI_H_
#define _ElementI_H_

#include "J2ObjC_header.h"
#include "NodeI.h"
#include "Element.h"

@protocol RXNamedNodeMap;
@protocol RXNodeList;
@protocol OrgW3cDomElement;

@interface ElementI : NodeI < RXElement >

#pragma mark Public

- (instancetype)initWithOrgW3cDomElement:(id<OrgW3cDomElement>)impl;

- (NSString *)getAttributeWithNSString:(NSString *)name;

- (id<RXNamedNodeMap>)getAttributes;

- (id<RXNodeList>)getChildNodes;

- (id<RXNodeList>)getElementsByTagNameWithNSString:(NSString *)name;

- (NSString *)getTagName;

- (jboolean)isNull;

@end

J2OBJC_EMPTY_STATIC_INIT(ElementI)

FOUNDATION_EXPORT void ElementI_initWithOrgW3cDomElement_(ElementI *self, id<OrgW3cDomElement> impl);

FOUNDATION_EXPORT ElementI *new_ElementI_initWithOrgW3cDomElement_(id<OrgW3cDomElement> impl) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ElementI)

typedef ElementI RXElementI;

#endif // _ElementI_H_
