/* Automatically generated by GNU msgfmt.  Do not modify!  */
package cz.natur.cuni.mirai.math.editor.locale;
public class Messages_en extends java.util.ResourceBundle {
  private static final java.lang.String[] table;
  static {
    java.lang.String[] t = new java.lang.String[218];
    t[0] = "";
    t[1] = "Project-Id-Version: miraimath-en-0.5\nReport-Msgid-Bugs-To: \nPOT-Creation-Date: 2008-12-28 18:55+0100\nPO-Revision-Date: 2009-01-05 19:24+0100\nLast-Translator: Bea Petrovicova\nLanguage-Team: English <LL@li.org>\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nX-Poedit-Language: English\n";
    t[4] = "&Export ...";
    t[5] = "&Export ...";
    t[6] = "&Save";
    t[7] = "&Save";
    t[10] = "Cut";
    t[11] = "Cut";
    t[12] = "&Copy";
    t[13] = "&Copy";
    t[16] = "About";
    t[17] = "About";
    t[22] = "Save changes?";
    t[23] = "Save changes?";
    t[24] = "Redo";
    t[25] = "Redo";
    t[26] = "&Help";
    t[27] = "&Help";
    t[28] = "Copy Te&X";
    t[29] = "Copy Te&X";
    t[36] = "New Vector ...";
    t[37] = "New Vector ...";
    t[40] = "&OK";
    t[41] = "&OK";
    t[44] = "The document has been modified. Save changes?";
    t[45] = "The document has been modified. Save changes?";
    t[46] = "Size:";
    t[47] = "Size:";
    t[52] = "&Undo";
    t[53] = "&Undo";
    t[54] = "LaTeX Document";
    t[55] = "LaTeX Document";
    t[56] = "Symbols";
    t[57] = "Symbols";
    t[58] = "&Array ...";
    t[59] = "&Array ...";
    t[66] = "&Delete";
    t[67] = "&Delete";
    t[68] = "&Formula";
    t[69] = "&Formula";
    t[76] = "&Cancel";
    t[77] = "&Cancel";
    t[78] = "&New";
    t[79] = "&New";
    t[80] = "Error! {0} not found. Installation incomplete.";
    t[81] = "Error! {0} not found. Installation incomplete.";
    t[82] = "&Matrix ...";
    t[83] = "&Matrix ...";
    t[84] = "New Array ...";
    t[85] = "New Array ...";
    t[86] = "A file named {0} already exists. Overwrite existing file?";
    t[87] = "A file named {0} already exists. Overwrite existing file?";
    t[90] = "General";
    t[91] = "General";
    t[92] = "&Contents";
    t[93] = "&Contents";
    t[94] = "Welcome! Read tutorial at http://mirai.sf.net";
    t[95] = "Welcome! Read tutorial at http://mirai.sf.net";
    t[98] = "Plain Text";
    t[99] = "Plain Text";
    t[100] = "Formula as PNG Image";
    t[101] = "Formula as PNG Image";
    t[102] = "Error";
    t[103] = "Error";
    t[108] = "Copy";
    t[109] = "Copy";
    t[110] = "New";
    t[111] = "New";
    t[118] = "&Save As ...";
    t[119] = "&Save As ...";
    t[120] = "&Edit";
    t[121] = "&Edit";
    t[124] = "HTML with PNG Images";
    t[125] = "HTML with PNG Images";
    t[126] = "Save";
    t[127] = "Save";
    t[128] = "&Insert";
    t[129] = "&Insert";
    t[140] = "Columns:";
    t[141] = "Columns:";
    t[142] = "Paste";
    t[143] = "Paste";
    t[144] = "&File";
    t[145] = "&File";
    t[148] = "&Open...";
    t[149] = "&Open...";
    t[152] = "Operators";
    t[153] = "Operators";
    t[154] = "Overwrite file?";
    t[155] = "Overwrite file?";
    t[166] = "Functions";
    t[167] = "Functions";
    t[172] = "Undo";
    t[173] = "Undo";
    t[178] = "&Paste";
    t[179] = "&Paste";
    t[180] = "Open";
    t[181] = "Open";
    t[186] = "New Matrix ...";
    t[187] = "New Matrix ...";
    t[190] = "&About ...";
    t[191] = "&About ...";
    t[194] = "&Vector ...";
    t[195] = "&Vector ...";
    t[196] = "&Cut";
    t[197] = "&Cut";
    t[206] = "Rows:";
    t[207] = "Rows:";
    t[208] = "&Redo";
    t[209] = "&Redo";
    t[210] = "Export";
    t[211] = "Export";
    t[212] = "E&xit";
    t[213] = "E&xit";
    t[216] = "Please, read install instructions http://mirai.sf.net";
    t[217] = "Please, read install instructions http://mirai.sf.net";
    table = t;
  }
  public java.lang.Object handleGetObject (java.lang.String msgid) throws java.util.MissingResourceException {
    int hash_val = msgid.hashCode() & 0x7fffffff;
    int idx = (hash_val % 109) << 1;
    {
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
    int incr = ((hash_val % 107) + 1) << 1;
    for (;;) {
      idx += incr;
      if (idx >= 218)
        idx -= 218;
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
  }
  public java.util.Enumeration getKeys () {
    return
      new java.util.Enumeration() {
        private int idx = 0;
        { while (idx < 218 && table[idx] == null) idx += 2; }
        public boolean hasMoreElements () {
          return (idx < 218);
        }
        public java.lang.Object nextElement () {
          java.lang.Object key = table[idx];
          do idx += 2; while (idx < 218 && table[idx] == null);
          return key;
        }
      };
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
